<script setup>
import { computed, ref } from 'vue';
import { useRoute, useRouter } from 'vue-router';
import BottomNav from '../../components/BottomNav.vue';
import AppButton from '../../components/common/AppButton.vue';
import { useAuthStore } from '../../store/auth/useAuthStore';
import historyIcon from '../../assets/images/category-history.png';
import cultureIcon from '../../assets/images/category-culture.png';
import natureIcon from '../../assets/images/category-nature.png';
import walkIcon from '../../assets/images/category-walk.png';
import forestImage from '../../assets/images/seoul-forest.png';

const route = useRoute(); const router = useRouter(); const authStore = useAuthStore(); const menuOpen = ref(false);
const isPreview = computed(() => route.query.preview === '1' || sessionStorage.getItem('previewMode') === 'true');
const isLoggedIn = computed(() => authStore.isAuthenticated || isPreview.value);
const categories = [{ label: '역사', image: historyIcon }, { label: '문화·예술', image: cultureIcon }, { label: '자연', image: natureIcon }, { label: '산책', image: walkIcon }];
const go = (name) => { menuOpen.value = false; router.push({ name }); };
</script>

<template><main class="home-page"><header><strong>투어 스위치</strong><div><button aria-label="검색">⌕</button><button aria-label="메뉴" @click="menuOpen=true">☰</button></div></header><section class="categories"><button v-for="item in categories" :key="item.label"><img :src="item.image" alt="" /><span>{{ item.label }}</span></button></section><section><h2>지금 서울은?</h2><article class="hero"><img :src="forestImage" alt="햇빛이 비치는 서울숲" /><div><strong>서울숲</strong><span>혼잡도 여유</span></div></article></section><section><h2>여유로운 관광지</h2><article class="spot"><img :src="forestImage" alt="서울숲" /><div><strong>서울숲</strong><span>자연 · 공원 · 산책</span></div></article></section><section v-if="isLoggedIn" class="ongoing"><div><span>투표 진행 중</span><strong>8월 15일 · 종로구 여행</strong><small>2 / 4명 투표 완료</small></div><AppButton size="small" @click="router.push({ name:'vote-status-show', params:{ roomId:'preview-room' } })">이어가기</AppButton></section><BottomNav /><div v-if="menuOpen" class="overlay" @click.self="menuOpen=false"><aside><header><button aria-label="닫기" @click="menuOpen=false">×</button><span>♧　⚙</span></header><template v-if="isLoggedIn"><div class="profile"><span>👤</span><strong>카카오톡 닉네임</strong></div></template><button v-else class="login" @click="go('login-show')">로그인</button><nav><small>여행</small><button @click="go('history-index')">여행 기록</button><button>오늘의 코스</button><button @click="go('room-create')">투표방(여행방) 만들기</button><template v-if="isLoggedIn"><small>계정</small><button @click="go('my-page-show')">회원 정보 수정</button></template></nav></aside></div></main></template>
<style scoped>.home-page{min-height:100vh;padding:20px 24px 80px;display:flex;flex-direction:column;gap:26px}.home-page>header{display:flex;justify-content:space-between;align-items:center}.home-page>header strong{font-size:21px}.home-page button{border:0;background:none}.home-page>header button{font-size:25px;margin-left:14px}.categories{display:flex;gap:14px;overflow:auto}.categories button{display:grid;gap:6px;min-width:62px}.categories img{width:54px;height:54px;padding:8px;object-fit:contain;border-radius:12px;box-shadow:var(--team-shadow-card)}h2{font-size:15px;margin-bottom:12px}.hero{height:220px;position:relative;border-radius:14px;overflow:hidden}.hero img{width:100%;height:100%;object-fit:cover}.hero:after{content:'';position:absolute;inset:45% 0 0;background:linear-gradient(transparent,#0009)}.hero div{position:absolute;z-index:1;left:16px;bottom:14px;color:#fff;display:grid}.hero span,.spot span{font-size:12px}.spot{display:flex;gap:14px;align-items:center}.spot img{width:104px;height:116px;object-fit:cover;border-radius:14px}.spot div{display:grid;gap:6px}.ongoing{padding:16px;border:1px solid #a9e7e8;border-radius:16px;display:flex;justify-content:space-between;align-items:center}.ongoing div{display:grid;gap:3px}.ongoing span{color:var(--team-color-primary);font-size:12px}.ongoing small{color:var(--team-color-gray-600)}.home-page :deep(.bottom-nav){position:fixed;max-width:430px;margin:auto}.overlay{position:fixed;z-index:10;inset:0;background:#0009}.overlay aside{margin-left:auto;width:70%;height:100%;background:#fff;padding:18px 26px}.overlay header{display:flex;justify-content:space-between;font-size:22px}.overlay header button{font-size:28px}.profile{display:grid;justify-items:center;gap:8px;margin:20px}.profile span{width:56px;height:56px;border-radius:50%;background:#ddd;display:grid;place-items:center}.login{display:block;margin:28px 0 28px auto;color:var(--team-color-primary);font-weight:700;font-size:17px}.overlay nav{display:grid;gap:18px;text-align:right}.overlay nav button{font-weight:700;font-size:16px}.overlay nav small{margin-top:12px;color:#999}</style>
